### ISSUE TITLE
Export 3D colored model

### ISSUE THREAD

**Issue by mgorakhiya-peak** [zeitraumdev/iPadLIDARScanExport#4]
Thanks for the sample project.
It really helps a lot.

I see that this sample code exports 3D objects but it's in grayed scale.

Can you help me, how can we generate a 3D model in actual colors (like realistic)?

I have seen that many apps are doing the same.
https://apps.apple.com/us/app/id1514382369
https://apps.apple.com/us/app/3d-scanner-app/id1419913995

**Comment by sp-zeitraum** [comment]
Hi @mgorakhiya-peak,

I'm glad the repo is helpful to you. Currently we have no plans to research in more in that direction, but if you want to look into it, now that time since the release of ARKit 3.5 has progressed, with 4 already being out and Unity picking it up, I would recommend you start there, in the ARFoundation Samples. They implemented Meshing with colors:
https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/manual/mesh-manager.html

![image](https://user-images.githubusercontent.com/48676215/100720975-0a545080-33bf-11eb-9a1e-dfda31fe128f.png)
